// Python script for the Clump Finding Problem

#!/usr/bin/python3
#Author: Mahima Arunkumar

import sys

#Accounting for the flags
sequence = sys.argv[2]
k = int(sys.argv[4])
L = int(sys.argv[6])
t = int(sys.argv[8])

#Read the file
file_path = sequence
with open(file_path) as f_obj:
    s = f_obj.read()

#Deliberatly chosen not to use .lower() in the following

#Mthod called clumpFinding
def clumpFinding( s, k, L, t ):
	#Initialize a list called out 
    out = []
    for start in range(len(s)-L+1):
        window = s[start:start+L]
        counts = {}
		#Same as in 'Präsenzaufgabe'
        for i in range(len(window)-k+1):
            if window[i:i+k] not in counts:
                counts[window[i:i+k]] = 0
            counts[window[i:i+k]] += 1
		#chech if kmer counts are above the threshold t, if so, then append it to list out
        for kmer in counts:
            if counts[kmer] >= t and kmer not in out:
                out.append(kmer)
    return out

#Format the result
new = ' '.join(clumpFinding(s,k,L,t))
list = new.split(" ")
print(list)


//Contains following output
//The output contains: ['ATGATCAAG', 'CTCTTGATC', 'TCTTGATCA', 'CTTGATCAT'] from the Moodle output aswell

"C:\Users\Mahima Arunkumar\PycharmProjects\ClumpFindingProblem\venv\Scripts\python.exe" "C:/Users/Mahima Arunkumar/PycharmProjects/ClumpFindingProblem/new.py" "C:\Users\Mahima Arunkumar\PycharmProjects\ClumpFindingProblem\Vibrio_cholerae.txt" 9 500 3
['AAAAAGCAG', 'AAAAGCAGC', 'TGTTTTTAT', 'TTGGTTTGG', 'AACAGAAAC', 'ACAGAAACA', 'CAGAAACAG', 'AGAAACAGA', 'GAAACAGAA', 'AAACAGAAA', 'ACAGCGAAA', 'TTGGAAGAG', 'AAAACGTTT', 'TTTTCGCCA', 'TGCTGGTGC', 'GTTCGATTC', 'AAAGCAGCT', 'AAGCAGCTG', 'CTGCTGCTG', 'TGCTGCTGC', 'GCTGCTGCT', 'AAAGAAGCT', 'AAGAAGCTG', 'ATGCGACAC', 'TGCGACACT', 'GCGACACTA', 'CGACACTAG', 'GACACTAGC', 'ACACTAGCT', 'CACTAGCTC', 'ACTAGCTCA', 'CTAGCTCAG', 'TAGCTCAGT', 'AGCTCAGTT', 'GCTCAGTTG', 'GAACCTCGT', 'AACCTCGTG', 'ACCTCGTGT', 'CCTCGTGTG', 'CTCGTGTGT', 'TCGTGTGTC', 'CGTGTGTCG', 'GTGTGTCGC', 'CTCAGTTGG', 'TCAGTTGGT', 'CAGTTGGTA', 'AGTTGGTAG', 'GTTGGTAGA', 'TTGGTAGAG', 'TGGTAGAGC', 'GGTAGAGCG', 'GTAGAGCGC', 'TAGAGCGCA', 'AGAGCGCAA', 'GAGCGCAAC', 'AGCGCAACC', 'GCGCAACCT', 'CGCAACCTT', 'GCAACCTTG', 'CAACCTTGC', 'AACCTTGCC', 'ACCTTGCCA', 'CCTTGCCAA', 'CTTGCCAAG', 'TTGCCAAGG', 'TGCCAAGGT', 'GCCAAGGTT', 'CCAAGGTTG', 'CAAGGTTGA', 'AAGGTTGAG', 'AGGTTGAGG', 'GGTTGAGGT', 'GTTGAGGTC', 'TTGAGGTCA', 'TGAGGTCAC', 'GAGGTCACG', 'AGGTCACGA', 'GGTCACGAG', 'GTCACGAGT', 'TCACGAGTT', 'CACGAGTTC', 'ACGAGTTCG', 'CGAGTTCGA', 'GAGTTCGAA', 'AGTTCGAAC', 'GTTCGAACC', 'TTCGAACCT', 'TCGAACCTC', 'CGAACCTCG', 'TGTGTCGCT', 'GTGTCGCTC', 'TGTCGCTCC', 'GTCGCTCCA', 'CTTAACGAT', 'GGACGCGGG', 'TGGAGCAGC', 'GGAGCAGCT', 'GAGCAGCTT', 'AGCAGCTTG', 'GCAGCTTGG', 'CAGCTTGGT', 'AGCTTGGTA', 'GCTTGGTAG', 'CTTGGTAGC', 'TTGGTAGCT', 'TGGTAGCTC', 'GGTAGCTCG', 'GTAGCTCGT', 'TAGCTCGTC', 'AGCTCGTCG', 'GCTCGTCGG', 'CTCGTCGGG', 'TCGTCGGGC', 'CGTCGGGCT', 'GTCGGGCTC', 'TCGGGCTCA', 'CGGGCTCAT', 'GGGCTCATA', 'GGCTCATAA', 'GCTCATAAC', 'CTCATAACC', 'TCATAACCC', 'CATAACCCG', 'ATAACCCGA', 'TAACCCGAA', 'AACCCGAAG', 'ACCCGAAGG', 'CCCGAAGGT', 'CCGAAGGTC', 'CGAAGGTCG', 'GAAGGTCGT', 'GGTTCAAAT', 'GTTCAAATC', 'TTCAAATCC', 'CCCGCAACC', 'CCGCAACCA', 'CGCAACCAA', 'GCAACCAAT', 'CAACCAATT', 'GACGAAGGT', 'TGCGTTTGC', 'GACCCTAGA', 'ACCCTAGAC', 'CCCTAGACC', 'CCTAGACCC', 'CTAGACCCT', 'TAGACCCTA', 'AGACCCTAG', 'TGGTGATGG', 'ACTGAGCTA', 'CTGAGCTAA', 'TGAGCTAAG', 'ACCTACTGA', 'CGGAATCGA', 'GGAATCGAA', 'GAATCGAAC', 'TGCTCTACC', 'GCTCTACCG', 'CTCTACCGA', 'TCTACCGAC', 'CTACCGACT', 'TACCGACTG', 'ACCGACTGA', 'CCGACTGAG', 'CGACTGAGC', 'GACTGAGCT', 'TTGTCGATT', 'TGTCGATTG', 'GTCGATTGT', 'TCGATTGTC', 'CGATTGTCG', 'GATTGTCGA', 'ATTGTCGAT', 'CATCTTCGT', 'ATCTTCGTC', 'AACCCAGAA', 'ACCCAGAAA', 'GGTTCGAAT', 'GTTCGAATC', 'TTCGAATCC', 'CGTAGCTCA', 'GTAGCTCAG', 'TAGCTCAGC', 'AGCTCAGCT', 'GCTCAGCTG', 'CTCAGCTGG', 'TCAGCTGGA', 'CAGCTGGAT', 'AGCTGGATA', 'GCTGGATAG', 'CTGGATAGA', 'TGGATAGAG', 'GGATAGAGT', 'GATAGAGTA', 'ATAGAGTAC', 'TAGAGTACC', 'AGAGTACCT', 'GAGTACCTG', 'CTACGAACC', 'TACGAACCA', 'ACGAACCAG', 'CGAACCAGG', 'GAACCAGGC', 'AACCAGGCG', 'ACCAGGCGG', 'CCAGGCGGT', 'CAGGCGGTC', 'AGGCGGTCA', 'GGCGGTCAG', 'GCGGTCAGA', 'CGGTCAGAG', 'GGTCAGAGG', 'GTCAGAGGT', 'TCAGAGGTT', 'CAGAGGTTC', 'AGAGGTTCG', 'GAGGTTCGA', 'AGGTTCGAA', 'TCGAATCCT', 'CGAATCCTC', 'GAATCCTCT', 'AATCCTCTC', 'ATCCTCTCG', 'AGTACCTGG', 'GTACCTGGC', 'TACCTGGCT', 'ACCTGGCTA', 'CCTGGCTAC', 'CTGGCTACG', 'TGGCTACGA', 'GGCTACGAA', 'GCTACGAAC', 'CGCGCCACT', 'CTGCAAATT', 'TGCAAATTG', 'TTAAACCAA', 'TTGGCGTGA', 'GAAGATCTG', 'AAGAAGCCG', 'GAAGTGAAA', 'AGTAAAAAA', 'TTTGTGGTC', 'ATTGATCGC', 'GCCAAGCGT', 'TACCTAAAA', 'ACCTAAAAC', 'AAAGGCTTC', 'TTTTTATAT', 'GAAAAAAAT', 'TATTAAAGA', 'TTATTTTTT', 'TATTTTTTT', 'AAAAAAAAT', 'ATAAAAAAA', 'TTTTTTTAA', 'ATCGCCACA', 'ATATGGTGG', 'TATGGTGGA', 'ATGGTGGAG', 'TGGTGGAGG', 'GGTGGAGGG', 'GTGGAGGGG', 'TGGAGGGGG', 'GGAGGGGGA', 'GAGGGGGAC', 'AGGGGGACG', 'GGGGGACGG', 'GGGGACGGA', 'GGGACGGAT', 'GGACGGATT', 'GACGGATTC', 'ACGGATTCG', 'CGGATTCGA', 'GGATTCGAA', 'GATTCGAAC', 'ATTCGAACC', 'TTCGAACCA', 'TCGAACCAT', 'CGAACCATC', 'GAACCATCG', 'AACCATCGA', 'ACCATCGAA', 'CCATCGAAG', 'CATCGAAGG', 'ATCGAAGGC', 'TCGAAGGCG', 'CGAAGGCGG', 'GAAGGCGGA', 'AAGGCGGAG', 'AGGCGGAGC', 'GGCGGAGCC', 'GCGGAGCCG', 'CGGAGCCGG', 'GGAGCCGGC', 'GAGCCGGCA', 'AGCCGGCAG', 'GCCGGCAGA', 'CCGGCAGAT', 'CGGCAGATT', 'GGCAGATTT', 'GCAGATTTA', 'CAGATTTAC', 'AGATTTACA', 'GATTTACAG', 'ATTTACAGT', 'TTTACAGTC', 'TTACAGTCT', 'TACAGTCTG', 'ACAGTCTGC', 'CAGTCTGCT', 'AGTCTGCTC', 'GTCTGCTCC', 'TCTGCTCCC', 'CTGCTCCCT', 'TGCTCCCTT', 'GCTCCCTTT', 'CTCCCTTTG', 'TCCCTTTGG', 'CCCTTTGGC', 'CCTTTGGCC', 'CTTTGGCCA', 'TTTGGCCAC', 'TTGGCCACT', 'TGGCCACTC', 'GGCCACTCG', 'GCCACTCGG', 'CCACTCGGG', 'CACTCGGGA', 'ACTCGGGAA', 'CTCGGGAAC', 'TCGGGAACC', 'CGGGAACCC', 'GGGAACCCC', 'GGAACCCCT', 'GAACCCCTC', 'AACCCCTCC', 'ACCCCTCCA', 'CCCCTCCAG', 'CCCTCCAGG', 'CCTCCAGGG', 'CTCCAGGGT', 'TTTTTCTTT', 'TTTTCTTTT', 'TTTCTTTTC', 'TTCTTTTCA', 'TTTTGAAAA', 'TTTGAAAAG', 'TTGAAAAGA', 'TGAAAAGAC', 'GAAAAGACT', 'AAAAGACTT', 'AAAGACTTA', 'AAGACTTAA', 'TGACGTTTT', 'GACGTTTTC', 'ACGTTTTCC', 'CGTTTTCCC', 'GTTTTCCCA', 'TTTTCCCAA', 'TTTCCCAAC', 'TTCCCAACG', 'TCCCAACGC', 'CCCAACGCA', 'CCAACGCAT', 'CAACGCATC', 'AACGCATCA', 'ACGCATCAA', 'CGCATCAAT', 'GCATCAATC', 'CATCAATCA', 'ATCAATCAA', 'TCAATCAAG', 'CAATCAAGG', 'AATCAAGGG', 'ATCAAGGGT', 'TCAAGGGTT', 'CAAGGGTTT', 'AAGGGTTTC', 'AGGGTTTCT', 'GGGTTTCTC', 'GGTTTCTCT', 'GTTTCTCTT', 'TTTCTCTTA', 'TTCTCTTAC', 'TCTCTTACG', 'CTCTTACGA', 'TCTTACGAG', 'CTTACGAGA', 'AATATGGTG', 'TCCAGGGTG', 'CCAGGGTGT', 'CAGGGTGTT', 'AGGGTGTTT', 'GGGTGTTTT', 'TTTATTTAT', 'TGAAAAAAT', 'TTTTTATTT', 'TGAAATTGA', 'GAGTACACC', 'AGTACACCG', 'GTACACCGA', 'TACACCGAA', 'ACACCGAAG', 'CACCGAAGA', 'ACCGAAGAA', 'CCGAAGAAG', 'CGAAGAAGA', 'GAAGAAGAT', 'AAGAAGATG', 'CAGTTAGAG', 'CAGAATCGG', 'AGAATCGGA', 'GAATCGGAA', 'AATCGGAAG', 'ATCGGAAGT', 'TCGGAAGTT', 'CGGAAGTTG', 'GGAAGTTGA', 'GAAGCCTTT', 'AAGCCTTTA', 'AGCCTTTAC', 'GCCTTTACC', 'CCTTTACCG', 'CTTTACCGA', 'TTTACCGAG', 'TTACCGAGC', 'TACCGAGCT', 'ACCGAGCTT', 'CCGAGCTTG', 'CGAGCTTGA', 'GAGCTTGAT', 'AGCTCGATT', 'GCTCGATTT', 'CTCGATTTA', 'TCGATTTAC', 'CGATTTACC', 'GCCTTGGCG', 'CCTTGGCGG', 'CTTGGCGGA', 'TTGGCGGAT', 'GCAGTTAGA', 'AGTTAGAGC', 'GTTAGAGCC', 'GAAGTTGAG', 'CTTGAGTTA', 'TTGAGTTAG', 'TGAGTTAGT', 'GAGTTAGTA', 'AGTTAGTAA', 'AAGTGAGCC', 'AGTGAGCCA', 'GTGAGCCAG', 'AGCTTGATG', 'GCTTGATGA', 'CCTGAGTAC', 'CTGAGTACA', 'TGAGTACAC', 'AGAAGATGC', 'GAAGATGCC', 'AAGATGCCT', 'AGATGCCTT', 'GATGCCTTG', 'ATGCCTTGG', 'TGCCTTGGC', 'TGGCGGATG', 'GGCGGATGC', 'CGCAGTTAG', 'CAGAGCTTG', 'AGAGCTTGA', 'GAGCTTGAG', 'GGAAGAAGC', 'GAAGAAGCC', 'AAGAAGCCT', 'TTAGAGCCT', 'TAGAGCCTG', 'AGAGCCTGC', 'GAGCCTGCC', 'AGCCTGCCG', 'AAGTTGAGC', 'AGTTGAGCC', 'GTTGAGCCA', 'TTGAGCCAG', 'TGAGCCAGA', 'GAGCCAGAG', 'AGCCAGAGC', 'GCCAGAGCT', 'CCAGAGCTT', 'AGCTTGAGC', 'GCTTGAGCT', 'GAGGAAGAA', 'CTCGATTTG', 'TCGATTTGC', 'CGATTTGCC', 'GATTTGCCT', 'ATTTGCCTG', 'TTTGCCTGA', 'TTGCCTGAG', 'TGCCTGAGT', 'GCCTGAGTA', 'GCGGATGCG', 'CGGATGCGC', 'GGATGCGCA', 'GATGCGCAG', 'ATGCGCAGT', 'TGCGCAGTT', 'GCGCAGTTA', [...]
